# Generated by Django 4.1.3 on 2022-12-07 02:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('first_name', models.CharField(max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=30, verbose_name='Sobrenome')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('is_waiting', models.BooleanField(default=False, verbose_name='Paciente está na fila de espera')),
                ('medical_record', models.TextField(default='', verbose_name='Prontuário')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
