# Generated by Django 4.1 on 2022-12-08 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_patient_is_waiting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 12, 8, 22, 38, 37, 118493, tzinfo=datetime.timezone.utc), verbose_name='Horário de chegada'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='med_record',
            field=models.JSONField(blank=True, default={}, verbose_name='Prontuário médico'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nutri_record',
            field=models.JSONField(blank=True, default={}, verbose_name='Prontuário nutricional'),
        ),
    ]
