# Generated by Django 4.1 on 2022-12-09 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_patient_arrival_time_alter_patient_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 12, 9, 0, 28, 26, 189022, tzinfo=datetime.timezone.utc), verbose_name='Horário de chegada'),
        ),
    ]
