# Generated by Django 4.1 on 2022-12-09 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_patient_arrival_time_alter_patient_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 12, 9, 0, 36, 27, 783184, tzinfo=datetime.timezone.utc), verbose_name='Horário de chegada'),
        ),
    ]
