# Generated by Django 4.1 on 2022-12-09 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_patient_arrival_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='patient',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 12, 9, 0, 38, 20, 311175, tzinfo=datetime.timezone.utc), verbose_name='Horário de chegada'),
        ),
    ]
