# Generated by Django 4.1 on 2022-12-12 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_patient_address_patient_email_patient_payment_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='birth',
            field=models.DateField(default=datetime.date(1997, 10, 19), verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='', max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 12, 12, 17, 5, 39, 789884, tzinfo=datetime.timezone.utc), verbose_name='Horário de chegada'),
        ),
    ]
