# Generated by Django 4.1.3 on 2022-12-21 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_patient_age_patient_birth_patient_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='arrival_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 12, 21, 19, 36, 57, 306139, tzinfo=datetime.timezone.utc), verbose_name='Horário de chegada'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nutri_record',
            field=models.JSONField(blank=True, default=dict, verbose_name='Prontuário nutricional'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='payment_record',
            field=models.JSONField(blank=True, default=dict, verbose_name='Histórico de pagamento'),
        ),
    ]
